lib <- file.path(Sys.getenv("LOCALAPPDATA"), "R", "win-library", paste0(R.version$major, ".", R.version$minor))
if (!dir.exists(lib)) dir.create(lib, showWarnings = FALSE, recursive = TRUE)
.libPaths(c(lib, .libPaths()))
pkgs <- c("rlang","httr","jsonlite","curl","openssl","httpuv")
install.packages(pkgs, repos = "https://cloud.r-project.org")
